### ISSUE TITLE
banner and minifyify clash

### ISSUE THREAD

**Issue by ccprog** [jmreidy/grunt-browserify#279]
I'm not sure if it's you or [minifyify](https://github.com/ben-ng/minifyify) to blame here, but this grunt config:
```javascript
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    licence: grunt.file.read('./LICENCE'),
    browserify: {
      options: {
        banner: '/*\n<%= licence %>*/\n',
        plugin: [ [ 'minifyify', {map: false } ] ],
      },
      mini: {
        src: 'index.js',
        dest: '<%= pkg.name %>.bundle.mini.js'
      },
    }
  });
```
ends with a `Fatal error: [bundle]  has no method 'copy'`, [bundle] beeing the completed and minified bundle. The bundle code dumped with the message seems to be otherwise working correctly.

Using either one of both options works just fine.

**Comment by tleunen** [comment]
It's an issue with `minifyify`. You should ask @ben-ng to change how `minifyify` works.
By default, the function [.bundle()](https://github.com/substack/node-browserify#bbundlecb) in browserify takes a function callbacks with 2 parameters, an error and a buffer.

When `minifyify` is used, the buffer parameter is not a Buffer object but a string, which causes `grunt-browserify` to throw an error when it tries to prepend the banner to the buffer.
Of course, we could fix it on our side, but `minifyify` should not change the way browserify works.

The issue seems to be at [this line in `minifyify`](https://github.com/ben-ng/minifyify/blob/master/lib/index.js#L85). So instead of str, it should be`new Buffer(str)`.

**Comment by ccprog** [comment]
reported as [#77](/ben-ng/minifyify/issues/77)

**Comment by ben-ng** [comment]
Thank you for finding this bug!
