### ISSUE TITLE
Maximum call stack size exceeded with Watchify

### ISSUE THREAD

**Issue by derek-duncan** [jmreidy/grunt-browserify#301]
I've been stumped on this error for a long time. I've pasted my browserify config below for reference. 

**Replication:**
When I start the task, the bundle is compiled initially. In the browser, it loads nicely, clean of errors. After I save a watched file, however, it rebundles successfully, but `Maximum call stack size exceeded` error appears in the console and none of my changes appear. 

If I disable the `watch: true` option, it works correctly. I think the issue is with Watchify adding some of the required files twice, causing the error.
```javascript
 browserify: {
      front_js: {
        files: {
          'public/js/build/bundle.js': ['public/js/src/**/*.jsx']
        },
        options: {
          bare: true,
          alias: [
            './public/js/lib/react/react-with-addons.js:react',
            './public/js/lib/flux/index.js:flux',
            './public/js/lib/react-router/dist/react-router.js:react-router',
            './public/js/lib/lodash/lodash.js:lodash'
          ],
          transform: [ require('grunt-react').browserify ],
          watch: true,
          keepAlive: true
        }
      }
    }
```

Any ideas?

**Comment by tleunen** [comment]
Hmm.. Never had this issue before, even with big projects.
I don't see anything incorrect in your config...

Could you give us more info?

**Comment by ggarek** [comment]
I have the same issue. The behaviour is exactly as derek-duncan described in **Replication** paragraph.

The difference is i am using gulp.

There is one more thing that could possible cause the issue. I have gulp tasks defined in *./tasks* path relative to *gulpfile.js*.

**Comment by ggarek** [comment]
I created a repo with clean [reproduction](https://github.com/ggarek/browserify-watchify-max-callstack-on-rebundle/tree/tasks-within-gulpfile) using ```gulp, browserify, watchify```.

There are two branches:
- [one](https://github.com/ggarek/browserify-watchify-max-callstack-on-rebundle/tree/tasks-within-gulpfile), where tasks are defined within gulpfile. 
- [other](https://github.com/ggarek/browserify-watchify-max-callstack-on-rebundle/tree/tasks-within-gulpfile), where tasks defined in separate folder.

In fact it occured that it does not matter. The last commit in each branch introduces the error. 
To be precise ```browserify.require``` causes the error.

One more thing, there is difference in bundle.js file after running gulp task and after rebundle. Seems it can tell much about origin of the issue. **The difference is in several latter bundle.js lines.**

### Bundle.js tail after  first run
```javascript
<...>
exports.is = {
  number: isNumber
};

},{}]},{},["./src/main.js"]);
```

### Bundle.js tail after rebundle
```javascript
<...>
exports.is = {
  number: isNumber
};

},{}],"utils":[function(require,module,exports){
arguments[4]["utils"][0].apply(exports,arguments)
},{}]},{},["./src/main.js"]);
```

* i included common ```exports.is = ...``` part to give little more context to snippets.

-----

I understand that it is *grunt-browserify thread* and i am sorry for interrupting with my gulpish code.

And i understand that issue can be caused by mistreatment of ```browserify/watchify```, i mean call order or some options could be wrong.

But the issue still throws sand in the wheels! So any help would be much appreciated! :pray:

**Comment by ggarek** [comment]
Looked through watchify issues.

Seems these could be correlated. All of these issues are about ```watchify + .require```.

substack/watchify#72
substack/watchify#74
substack/watchify#130
substack/watchify#148

It seems that watchify does not play well with ```.require``` and ```.external```. I did not find the solution though. :disappointed:

**Comment by jslatts** [comment]
@ggarek I am seeing the exact same issue using Gulp and Watchify. Works fine first build, then after a change triggers a rebuild via watchify, I get the maximum call stack size exceeded error. I am working around the issue by just not using watchify and triggering a rebuild with gulp-watch, but this is obviously much slower. Did you make any headway?

**Comment by tleunen** [comment]
It seems to be a bug with `watchify` then.

**Comment by derek-duncan** [comment]
I was able to avoid this issue with two bundles: main and vendor. Put all of your dependancies inside the vendor bundle and do not run watchify on it (sometimes double inserts when required). You should rarely be changing the vendor dependencies, so just rebuild it when you do.

**Comment by ggarek** [comment]
@derek-duncan

Yeah, this will work for vendor libs, but it wont work with your own libs that are logically external for main package. 
E.g. i have single repo with client and server packages and there are several shared libs, so while working on client for example i might need to fix a shared lib.. you see.

@tleunen yeah it is, and it seems there is no work on this issue going on.
@jslatts i ended up with same gulp-watch slowiiish approach, that`s sad. :disappointed:

**Comment by dfcreative** [comment]
+1.
Faced the same issue using [dialog-component](https://github.com/component/dialog) and [component-tip](https://github.com/component/tip) in the project. The components use [stringify](https://github.com/JohnPostlethwait/stringify) and [html-browserify](https://github.com/duckbox/html-browserify) transforms to precompile templates.
First time I launch watchify it compiles the whole project correctly, and if I change anything within the nested requirement (`feedback.js`), I get `Maximum call stack size exceeded`.
The structure of dependencies looks like:
```
index.js
- component-tip
- ./feedback.js
  - dialog-component
```

**Comment by dfcreative** [comment]
I've come up with `watch 'npm run build' '.' --wait=1` command, using [watch](https://www.npmjs.com/package/watch), and it seems to be a nice workaround.

**Comment by michaelBenin** [comment]
We ran into this problem a while back after our build had more than 200+ files.

The fix was:

    echo 'kern.maxfiles=20480' | sudo tee -a /etc/sysctl.conf && echo -e 'limit maxfiles 8192 20480\nlimit maxproc 1000 2000' | sudo tee -a /etc/launchd.conf && echo 'ulimit -n 4096' | sudo tee -a /etc/profile
