### ISSUE TITLE
external sourcemaps

### ISSUE THREAD

**Issue by tnguyen14** [jmreidy/grunt-browserify#307]
Is there a way to generate external sourcemaps with this plugin?

**Comment by tleunen** [comment]
Nop, but you can use [Exorcist](https://github.com/thlorenz/exorcist) to externalize the inlined sourcemap from the bundle.

**Comment by tnguyen14** [comment]
I was able to extract it using [grunt-external-sourcemap](https://github.com/goodeggs/grunt-external-sourcemap), but unfortunately it doesn't work when `watch: true`.

**Comment by tleunen** [comment]
Running `exorcist` in the `postBundleCB` should work.. Did you try that?

**Comment by tnguyen14** [comment]
@tleunen do you have an example of how that config would look like?

**Comment by tleunen** [comment]
Hmm, the problem is that inside `postBundleCB`, the destination file is not created yet.
But what you can do is, based on the string buffer, get the inlined sourcemap, replace it by the reference to another file, and write the sourcemap inside another file.

If there were a hook to run something when the bundle is complete, you could run `grunt-external-sourcemap` but unfortunately, it's not the case.

Why would you like to get the sourcemap in another file while using `watch: true`?

**Comment by tnguyen14** [comment]
Yeah that's a great question. I personally wouldn't mind if it's inline. However, in the office, we use Eclipse as the company standard IDE and it tends to crash when trying to open a compiled JS file with inline sourcemaps.

**Comment by tleunen** [comment]
I think your best bet is to let the sourcemap inside the bundle, and then run another task to extract the sourcemap from the bundle.

So try to use `grunt-contrib-watch` to watch your bundle file, and as soon as the file changed, run `grunt-external-sourcemap` to extract it.
