### ISSUE TITLE
Release 4.0.0

### ISSUE THREAD

**Issue by jonbretman** [jmreidy/grunt-browserify#320]
It would be awesome to get a release out with the upgrade to watchify 3.0.0 which adds support for using browserify inside virtual environments like Docker. Since this was a major update to watchify it should probably be a major update to grunt-browserify.

**Comment by tleunen** [comment]
I published it as 3.7.0, because even if watchify had a "big" upgrade, we didn't change anything inside `grunt-browserify` to make it work with the new version, so I don't think a major update is really needed in this case.

I forgot to update the changelog as well, I'll do it later this week or early next week. I'm a bit busy at the moment.

**Comment by jonbretman** [comment]
Ok cool, makes sense. Thanks.
