### ISSUE TITLE
ngCordova / iOS App - AppStore Submission

### ISSUE THREAD

**Issue by khellhake** [jmreidy/grunt-browserify#381]
Interesting issue -
I've build an app using angular, material design, ngCordova etc.  Using browserify for my build and combining my .js files into 1 bundle file.  All goes well until I went to submit it through the App Store upload process.  It validates fine, but gets to the very last step and throws an error.  See below --
No Idea what would cause this, but I just removed grunt-browserify before doing my cordova build. fixed it!

![screen shot 2016-04-27 at 2 08 20 pm](https://cloud.githubusercontent.com/assets/3502205/14897495/2d8ed4de-0d50-11e6-9d8d-e0740ea2770f.png)

**Comment by DirtyHairy** [comment]
Hi khellhake!

This is not an issue with `grunt-browserify`. What is happening here is that the `node_modules` tree contains binary dependencies which are scanned and rejected. The fact that the error is caused by a depedency of `grunt-browserify` is mere coincidence. Imho packaging build time dependencies in your cordova project is not a good idea anyway, I would consider building outside `www` and copying the build artifacts at the end of your build chain.

Cheers
    -Christian
