### ISSUE TITLE
support using browserify-lite as an option

### ISSUE THREAD

**Issue by pravi** [jmreidy/grunt-browserify#387]
debian currently only have browserify-lite and not full browserify, it would be a great help if we can use browserify-lite easily in place of browserify.

**Comment by DirtyHairy** [comment]
Hi @pravi! Can you help me to understand the problem here? grunt-browserify is installed via NPM and pulls browserify as a dependency, there is no need for any distro-installed packages.

**Comment by pravi** [comment]
@DirtyHairy we want to provide native debian packages for apps like gitlab, diaspora, pagure, prometheus etc (so users can just use debian's package manager apt to install these packages). This makes life easier for users who are not familiar with package managers of each of these languages like npm, rubygems or go get. These apps need browserified versions of libraries like fuzzaldrin-plus, handlebars etc. We should be able to build these packages using the tools available as native packages. If we want to use browserify, we have to create a native package of browserify first, which means creating native packages for all its long list of dependencies. browserify-lite has a smaller list of dependencies and it is already available as a native debian package. You can also read this thread -> https://github.com/LeoIannacone/npm2deb/issues/11 to understand why we convert npm packages to deb packages.

**Comment by DirtyHairy** [comment]
Hi @pravi !

I have only the highest respect for Debian, but I really think that attempting to repackage NPM packages as debs is as futile as rolling sisyphos' stone :pensive:. I am very aware of NPMs shortcomings as a package manager, but attempting to globally pin package versions with apt is orthogonal to NPMs philosophy and is almost guaranteed to cause a plethora of issues. As a developer and maintainer of NPM packages, I would never risk to support this way of running my packages :smirk:

That said, in what way would you like `grunt-browserify` to support  `browserify-lite` --- what do you propose?

Cheers
-Christian

**Comment by pravi** [comment]
@DirtyHairy Indeed, it would create problems, we are prepared to face it. We need to make sure all reverse dependencies of a module are updated at the same time to use the same version. Yes, it is a lot of work, we may have to patch some modules to work with newer version of its dependencies, but we have chosen that to provide the same install experience to our users. We are not expecting the upstreams to support this configuration, only request is usually to update dependencies to newer versions.

We are not going to package all the npm modules, but only those we really require like dependencies of grunt, gulp, ava etc. These are to make sure we browerify the libraries we use in apps like gitlab, diaspora, prometheus are built using native tools (ie, all the apps we ship has the full source code and can be rebuilt using the tools available in debian).

It would be good if it just requires loading `grunt.loadNpmTasks('grunt-browserify-lite')` instead of `grunt.loadNpmTasks('grunt-browserify')` in Gruntfile.js/cofee.

**Comment by pravi** [comment]
Its a battle between the convenience of developers and convenience of users, we chose to side with users.

**Comment by DirtyHairy** [comment]
Hi @pravi !

I respect your descisions, but I don't think that this policy is of any benefit to users, quite the contrary. It would be much more convenient for everyone involved, including the users, if you would just use NPM during build (possibly fixing dependencies with a shrinkwrapper) and bundle any runtime dependencies in the resulting deb.

Conserning your suggestion: there's nothing we can do to achieve this, it would require installing a version of `grunt-browserify` patched to use `browserify-lite` under the prefix `grunt-browserify-lite` in node's search path (of course, you could provide this as a patched package). Switching to `browserify-lite` instead of `browserify` on our end is out of the questions as `browserify-lite` supports almost none of the features `browserify` offers (most projects would simply fail to build).

Have you considered symlinking `browserify-lite` to `browserify`, either globally or locally during build? This will not resolve any build issues related to `browserify-lite`, but it would allow to switch the build transparently to `browserify-lite`.
